services:
  client-react-vite:
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    image: client-react-vite
    build:
      context: ./client-react/
      dockerfile: ./../ClientReactDockerfile
    init: true
    volumes:
      - ./client-react:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - frontend
    ports:
      - 5173:5173
  client-react-nginx:
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    image: client-react-nginx
    build:
      context: ./client-react/
      dockerfile: ./../ClientReactNginxDockerfile
    init: true
    networks:
      - frontend
    ports:
      - 80:8080
    restart: unless-stopped
  api-node:
    image: api-node
    build:
      context: ./api-node/
      dockerfile: ./../ApiNodeDockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./api-node/
        target: /usr/src/app/
      - type: volume
        target: /usr/src/app/node_modules
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    networks:
      - frontend
      - backend
    ports:
      - 3000:3000
    restart: unless-stopped
  api-golang:
    image: api-golang
    build:
      context: ./api-golang/
      dockerfile: ./../ApiGolangDockerfile
      target: dev
    init: true
    volumes:
      - type: bind
        source: ./api-golang/
        target: /app/
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@db:5432/postgres
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    networks:
      - frontend
      - backend
    ports:
      - 8080:8080
    restart: unless-stopped
  db:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    networks:
      - backend
    ports:
      - 5432:5432
volumes:
  pgdata:
networks:
  frontend:
  backend: